// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file authzed/api/v1alpha1/schema.proto (package authzed.api.v1alpha1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * ReadSchemaRequest is the required data to read Object Definitions from
 * a Schema.
 *
 * @generated from message authzed.api.v1alpha1.ReadSchemaRequest
 */
export class ReadSchemaRequest extends Message<ReadSchemaRequest> {
  /**
   * The list of names of the Object Definitions that are being requested.
   *
   * These names must be fully qualified with their namespace (e.g.
   * myblog/post).
   *
   * @generated from field: repeated string object_definitions_names = 1;
   */
  objectDefinitionsNames: string[] = [];

  constructor(data?: PartialMessage<ReadSchemaRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "authzed.api.v1alpha1.ReadSchemaRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "object_definitions_names", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReadSchemaRequest {
    return new ReadSchemaRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReadSchemaRequest {
    return new ReadSchemaRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReadSchemaRequest {
    return new ReadSchemaRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ReadSchemaRequest | PlainMessage<ReadSchemaRequest> | undefined, b: ReadSchemaRequest | PlainMessage<ReadSchemaRequest> | undefined): boolean {
    return proto3.util.equals(ReadSchemaRequest, a, b);
  }
}

/**
 * ReadSchemaResponse is the resulting data after having read the Object
 * Definitions from a Schema.
 *
 * @generated from message authzed.api.v1alpha1.ReadSchemaResponse
 */
export class ReadSchemaResponse extends Message<ReadSchemaResponse> {
  /**
   * The Object Definitions that were requested.
   *
   * @generated from field: repeated string object_definitions = 1;
   */
  objectDefinitions: string[] = [];

  /**
   * The computed revision of the returned object definitions.
   *
   * @generated from field: string computed_definitions_revision = 2;
   */
  computedDefinitionsRevision = "";

  constructor(data?: PartialMessage<ReadSchemaResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "authzed.api.v1alpha1.ReadSchemaResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "object_definitions", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "computed_definitions_revision", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReadSchemaResponse {
    return new ReadSchemaResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReadSchemaResponse {
    return new ReadSchemaResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReadSchemaResponse {
    return new ReadSchemaResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ReadSchemaResponse | PlainMessage<ReadSchemaResponse> | undefined, b: ReadSchemaResponse | PlainMessage<ReadSchemaResponse> | undefined): boolean {
    return proto3.util.equals(ReadSchemaResponse, a, b);
  }
}

/**
 * WriteSchemaRequest is the required data used to "upsert" the Schema of a
 * Permissions System.
 *
 * @generated from message authzed.api.v1alpha1.WriteSchemaRequest
 */
export class WriteSchemaRequest extends Message<WriteSchemaRequest> {
  /**
   * The Schema containing one or more Object Definitions that will be written
   * to the Permissions System.
   *
   * 256KiB
   *
   * @generated from field: string schema = 1;
   */
  schema = "";

  /**
   * If specified, the existing revision of object definitions in the schema that must be present for
   * the write to succeed. If the revision specified differs (i.e. the underlying schema has changed),
   * the write call will fail with a FAILED_PRECONDITION error.
   *
   * @generated from field: string optional_definitions_revision_precondition = 2;
   */
  optionalDefinitionsRevisionPrecondition = "";

  constructor(data?: PartialMessage<WriteSchemaRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "authzed.api.v1alpha1.WriteSchemaRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "schema", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "optional_definitions_revision_precondition", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WriteSchemaRequest {
    return new WriteSchemaRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WriteSchemaRequest {
    return new WriteSchemaRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WriteSchemaRequest {
    return new WriteSchemaRequest().fromJsonString(jsonString, options);
  }

  static equals(a: WriteSchemaRequest | PlainMessage<WriteSchemaRequest> | undefined, b: WriteSchemaRequest | PlainMessage<WriteSchemaRequest> | undefined): boolean {
    return proto3.util.equals(WriteSchemaRequest, a, b);
  }
}

/**
 * WriteSchemaResponse is the resulting data after having written a Schema to
 * a Permissions System.
 *
 * @generated from message authzed.api.v1alpha1.WriteSchemaResponse
 */
export class WriteSchemaResponse extends Message<WriteSchemaResponse> {
  /**
   * The names of the Object Definitions that were written.
   *
   * @generated from field: repeated string object_definitions_names = 1;
   */
  objectDefinitionsNames: string[] = [];

  /**
   * The computed revision of the written object definitions.
   *
   * @generated from field: string computed_definitions_revision = 2;
   */
  computedDefinitionsRevision = "";

  constructor(data?: PartialMessage<WriteSchemaResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "authzed.api.v1alpha1.WriteSchemaResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "object_definitions_names", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "computed_definitions_revision", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WriteSchemaResponse {
    return new WriteSchemaResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WriteSchemaResponse {
    return new WriteSchemaResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WriteSchemaResponse {
    return new WriteSchemaResponse().fromJsonString(jsonString, options);
  }

  static equals(a: WriteSchemaResponse | PlainMessage<WriteSchemaResponse> | undefined, b: WriteSchemaResponse | PlainMessage<WriteSchemaResponse> | undefined): boolean {
    return proto3.util.equals(WriteSchemaResponse, a, b);
  }
}

